[package]
name = "actix-web-actors"
version = "4.0.0-beta.6"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix actors support for Actix Web"
keywords = ["actix", "http", "web", "framework", "async"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "actix_web_actors"
path = "src/lib.rs"

[dependencies]
actix = { version = "0.12.0", default-features = false }
actix-codec = "0.4.0"
actix-http = "3.0.0-beta.8"
actix-web = { version = "4.0.0-beta.8", default-features = false }

bytes = "1"
bytestring = "1"
futures-core = { version = "0.3.7", default-features = false }
pin-project = "1.0.0"
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
actix-rt = "2.2"
actix-test = "0.1.0-beta.3"

awc = { version = "3.0.0-beta.7", default-features = false }
env_logger = "0.8"
futures-util = { version = "0.3.7", default-features = false }
